# Generated by Django 4.2.8 on 2023-12-26 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_date_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 26, 16, 12, 43, 183283), verbose_name='Дата публикации'),
        ),
    ]
