# Generated by Django 4.2.6 on 2023-12-11 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_date_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 11, 12, 54, 17, 350703), verbose_name='Дата публикации'),
        ),
    ]
