# Generated by Django 4.2.8 on 2023-12-17 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 17, 20, 28, 36, 558190), verbose_name='Дата публикации'),
        ),
    ]
