# Generated by Django 4.2.8 on 2023-12-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='account_images'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Not answered')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telegram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='vk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
